### ISSUE TITLE
cannot find module express

### ISSUE THREAD

**Issue by waelHamed** [kweiberth/react-todo-list#9]
hi 

i cloned the react-todo-list and when i tried to execute the command 

node server.js 

the next error appear in my cmd 

> C:\Users\wael\Documents\react-todo-list\server>node server.js
> module.js:457
>     throw err;
>     ^
> 
> Error: Cannot find module 'express'
>     at Function.Module._resolveFilename (module.js:455:15)
>     at Function.Module._load (module.js:403:25)
>     at Module.require (module.js:483:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (C:\Users\wael\Documents\react-todo-list\server\server
> .js:1:77)
>     at Module._compile (module.js:556:32)
>     at Object.Module._extensions..js (module.js:565:10)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
> 
> C:\Users\wael\Documents\react-todo-list\server>

also i wish to ask about that part-3-start part because i don't know what is that . 

thanks in advance .

**Comment by kweiberth** [comment]
@maskspy make sure you run `npm install` in the project directory. This will download all of the required dependencies listed in the `package.json` file. 

There are many branches in this repository, each corresponding to the start of one of my video lessons. `part-3-start` branch is the state of the repo at the start of my Part 3 lesson.

**Comment by kkodali** [comment]
For branches try git checkout part-3-start then you have to root again into that folder and go through following to avoid the error you mentioned.
run : npm install
run: node server/server.js
run: npm run serve
Now open you browser localhost:3000 you should be good to go.

In simple words, your command should be "node server/server.js"
